### ISSUE TITLE
Merge similar catch blocks

### ISSUE THREAD

**Issue by lprone** [M-Sin/CircuitBuilder#9]
https://github.com/M-Sin/CircuitBuilder/blob/38672a3dc7d9e044420d43ae637803568bb35b2a/CircuitBuilder/src/circuit/UserMain.java#L171

You can catch to different exceptions with same block as:
`
} catch (IllegalArgumentException | ArrayIndexOutOfBoundsException e) {
`

**Comment by M-Sin** [comment]
Done! Thank you.
